#pragma once

struct NerpsListNode {
    struct NerpsListNode *next;
    unsigned int field_4;
    unsigned int field_8;
    unsigned int field_c;
    unsigned int field_10;
};

struct SortNode {
    struct SortNode *next;
    int val;
};

struct StringHolder;
struct Vec4;
struct NerpsArg;
struct WrapperNode;
struct Ctx6b0;
struct AppendArgC;
struct AppendArg10;

void SetScriptFeature(unsigned int param_1, unsigned int param_2);
void FUN_0046a140(int index, unsigned int param_2, unsigned int param_3);
void SetScriptStopped(unsigned int param_1);
unsigned int IsScriptStopped(void);
void RunLevelScript(void);
struct NerpsListNode *FUN_0046b4f0(unsigned int param_1);
void FUN_0046b520(struct WrapperNode *node);
int RemoveScriptSection(struct SortNode *node);
void InsertScriptSection(struct SortNode *node);
void FUN_0046b6b0(struct Ctx6b0 *ctx, unsigned int param_2);
void AppendObjectiveEventList(struct AppendArgC *arg);
void AppendSectionRewards(struct AppendArg10 *arg);
void FUN_0046b650(const char *src, struct StringHolder *holder);
unsigned int FUN_0046b700(void);
unsigned int FUN_0046b760(void);
void NewScriptGiveEvent(unsigned int param_1, unsigned int param_2);
void NewScriptTakeEvent(unsigned int param_1);
void NewScriptAddBricksEvent(unsigned int param_1);
void NewScriptCurrencyEvent(unsigned int param_1);
void NewScriptPlaceEvent(unsigned int param_1, unsigned int *param_2, unsigned int param_3);
void NewScriptClearEvent(struct Vec4 *param_1);
void NewScriptUnglueEvent(struct Vec4 *param_1);
void NewScriptGlueEvent(struct Vec4 *param_1);
void NewScriptExtendParkEvent(struct Vec4 *param_1);
void NewScriptFmvEvent(unsigned int param_1);
void NewScriptIntervalEvent(unsigned int param_1);
void NewScriptMessageEvent(unsigned int param_1);
void NewScriptFeatureEvent(unsigned int param_1, unsigned int param_2);
void NewScriptReportEvent(unsigned int param_1, unsigned int param_2, unsigned int param_3);
void FUN_0046bad0(unsigned int param_1, unsigned int param_2, unsigned int *param_3);
void NewScriptWorkersEvent(unsigned int param_1, unsigned int param_2);
void NewScriptDegradeEvent(unsigned int param_1, unsigned int param_2, unsigned int param_3);
void FUN_0046bb80(unsigned int param_1, unsigned int param_2);
void NewScriptCapacityScaleEvent(unsigned int param_1, unsigned int param_2);
void NewScriptCapacityCapEvent(unsigned int param_1, unsigned int param_2);
void NewScriptEntranceFeeEvent(unsigned int param_1);
void NewScriptEndLevelEvent(void);
void NewScriptPurgeEvent(void);
void NewScriptThemeIconEvent(unsigned int param_1, unsigned int param_2);
void NewScriptAddFlagEvent(unsigned int param_1, unsigned int param_2);
void NewScriptBridgesEvent(unsigned int param_1, unsigned int param_2);
void NewScriptBriefingFileEvent(unsigned int param_1);
void NewScriptHintsFileEvent(unsigned int param_1);
void FUN_0046bd70(unsigned int param_1, unsigned int param_2);
void NewScriptLookAtEvent(unsigned int *param_1);
void NewScriptNeedEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3);
void NewScriptNeedAtEvent(unsigned char param_1, unsigned int param_2, unsigned int *param_3);
void NewScriptNeedInEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3, struct Vec4 *param_4);
void NewScriptConnectEvent(unsigned char param_1, unsigned int param_2);
void NewScriptLinkEvent(unsigned char param_1, unsigned int param_2);
void NewScriptRangeEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3, unsigned int param_4);
void NewScriptClearAreaEvent(unsigned char param_1, struct Vec4 *param_2, unsigned int param_3);
void NewScriptRemoveEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3);
void NewScriptRemoveRangeEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3, unsigned int param_4);
void NewScriptCompositeEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3, unsigned int param_4);
void NewScriptLoopCompositeEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3);
void NewScriptTechLevelEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3);
void NewScriptParkVisitorsEvent(unsigned char param_1, unsigned int param_2);
void NewScriptRideVisitorsEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3);
void NewScriptRidersEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3);
void NewScriptSceneryCoverageEvent(unsigned char param_1, unsigned int param_2);
void NewScriptPathSceneryEvent(unsigned char param_1, unsigned int param_2);
void NewScriptRideCoverageEvent(unsigned char param_1, unsigned int param_2);
void NewScriptShopCoverageEvent(unsigned char param_1, unsigned int param_2);
void NewScriptFoodCoverageEvent(unsigned char param_1, unsigned int param_2);
void NewScriptTotalCoverageEvent(unsigned char param_1, unsigned int param_2);
void NewScriptStudAreaEvent(unsigned char param_1, struct Vec4 *param_2, unsigned int param_3);
void NewScriptSaveEvent(unsigned char param_1, unsigned int param_2);
void NewScriptHappinessEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3);
void NewScriptNeedGardenersEvent(unsigned char param_1, unsigned int param_2);
void NewScriptNeedMechanicsEvent(unsigned char param_1, unsigned int param_2);
void NewScriptHungerEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3, unsigned int param_4);
void NewScriptFixRidesEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3);
void NewScriptPowerRidesEvent(unsigned char param_1, unsigned int param_2);
void NewScriptZoningEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3);
void NewScriptCheckFlagEvent(unsigned char param_1, unsigned int param_2, unsigned int param_3);
void NewScriptSelectThemeEvent(unsigned char param_1, unsigned int param_2);
void NewScriptSelectTabEvent(unsigned char param_1, unsigned int param_2);
void NewScriptSelectModeEvent(unsigned char param_1, unsigned int param_2);
void NewScriptForeverEvent(unsigned char param_1);
void FUN_0046c5c0(void);
unsigned int FUN_0046cb20(void);
void FUN_0046ce00(void);
unsigned int SaveScripts(void);
unsigned int LoadScripts(void);
